name: C/C++ CI
env: 
  DEPLOY_PACKAGE_NAME : "Application_executable_${{ github.sha }}.zip"

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Git clone Repo
      uses: actions/checkout@v1
      
    - name: List curent folder
      run: ls -la
      
    - name: move to src and make file
      run: |
        cd src
        ls -la
        make
      
    - name: Create ZIP package Repo
      run: |
        cd build/
        zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -i *graph*
        
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "~/build/${{ env.DEPLOY_PACKAGE_NAME }}"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"  
